### ISSUE TITLE
Documentation on the process to draft a new newsletter

### ISSUE THREAD

**Issue by emmyft** [osc-delft/newsletters#3]
When should we do what? Who do we need to ask when to collect the entries? How is this process going to work on GitHub (e.g. first open a new document, link to PR to issue(s) collecting newsletter items...? )

Good places to see how it has been done:
- The Turing Way: [issues](https://github.com/alan-turing-institute/the-turing-way/issues/1221) and PRs(https://github.com/alan-turing-institute/the-turing-way/pull/1452)
- OBF: [repo](https://github.com/OBF/newsletter)

This probably needs to be done before #2

**Comment by malvikasharan** [comment]
@emmyft have you had a look at this: https://the-turing-way.netlify.app/community-handbook/newsletters.html? I often review Turing Way's Twitter feed to find out different things that have happened throughout.

**Comment by emmyft** [comment]
Thank you so much @malvikasharan - haven't come across your documentation, but it is so inspiring and handy (:

**Comment by emmyft** [comment]
Now in readme.md (:
